# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43e75a746759d0a1e756f7ea4a31f84dcf3fe99a100e7f13f5fa358c3ac595d7362e49a6325b3d5ab908331c9fe748632c1a8531867adaf51de336c17bb4a588

test:
  secret_key_base: 344cc487caa9dfbb6d850563779e6cf48f00cdd2510cd178db6ab6cfcf371c5be7b31424f5ddf16c064fcfbf6e73d6420d75a03af570ba41b4056892b8b28c15

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
